#!/usr/bin/env sh

cd $HOME

# Useful dirs.
mkdir -p temp/ workspace/

mkdir -p .config/nvim/
ln -sf ~/dotfiles/init.vim .config/nvim/init.vim

mkdir -p .config/ranger/
ln -sf ~/dotfiles/rc.conf .config/ranger/rc.conf

mkdir -p .ctags.d/
ln -sf ~/dotfiles/general.ctags .ctags.d/general.ctags

ln -sf ~/dotfiles/tmux.conf .tmux.conf
ln -sf ~/dotfiles/gitignore_global .gitignore_global

ln -sf ~/dotfiles/aliases.zsh ~/dotfiles/env_vars.zsh ~/dotfiles/functions.zsh .oh-my-zsh/custom/
