#!/usr/bin/env sh

cd $HOME

mkdir -p .config/nvim/
ln -sf ~/dotfiles/init.vim .config/nvim/init.vim
ln -sf ~/dotfiles/_plugins.vim .config/nvim/_plugins.vim
ln -sf ~/dotfiles/_colors-italics.vim .config/nvim/_colors-italics.vim
ln -sf ~/dotfiles/_keymaps.vim .config/nvim/_keymaps.vim
ln -sf ~/dotfiles/_plugins-settings.vim .config/nvim/_plugins-settings.vim

mkdir -p .config/ranger/
ln -sf ~/dotfiles/rc.conf .config/ranger/rc.conf

mkdir -p .ctags.d/
ln -sf ~/dotfiles/general.ctags .ctags.d/general.ctags

mkdir -p .config/alacritty/
ln -sf ~/dotfiles/alacritty.yml .config/alacritty/alacritty.yml

mkdir -p .oh-my-zsh/custom/
ln -sf ~/dotfiles/aliases.zsh ~/dotfiles/env_vars.zsh ~/dotfiles/functions.zsh .oh-my-zsh/custom/

ln -sf ~/dotfiles/tmux.conf .tmux.conf
ln -sf ~/dotfiles/gitignore_global .gitignore_global

# Useful dirs.
mkdir -p temp/ workspace/
