# To install, run:
# brew bundle

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"

brew "asciinema"
brew "cmake"
brew "coreutils"
brew "direnv"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "httpie"
brew "lazygit"
brew "less"
brew "openssl@1.1"
brew "neovim"
brew "node"
brew "pnpm"
brew "readline"
brew "ripgrep"
brew "spaceship"
brew "tmux"
brew "tmuxp"
brew "tree"
brew "watch"
brew "watchman"
brew "yarn"
brew "zlib"
brew "zsh"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

cask "alacritty"
cask "brave-browser"
cask "figma"
cask "firefox"
cask "flutter"
cask "flycut"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "krisp"
cask "ngrok"
cask "notion"
cask "qbserve"
cask "sketch"
cask "visual-studio-code"
