# To install, run:
# brew bundle

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"

brew "cmake"
brew "coreutils"
brew "direnv"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "httpie"
brew "openssl@1.1"
brew "neovim"
brew "node@14"
brew "ranger"
brew "readline"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "watch"
brew "yarn"
brew "zlib"
brew "zsh"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

cask "alacritty"
cask "firefox"
cask "flycut"
cask "github"
cask "google-chrome"
cask "krisp"
cask "qbserve"
cask "visual-studio-code"
