#!/usr/bin/env sh

read -p '> What is your Git user.email? (empty to keep current): ' git_email
if [ -n "$git_email" ]
  then
    git config --global --replace-all user.email "$git_email"
fi

read -p '> What is your Git user.name? (empty to keep current): ' git_name
if [ -n "$git_name" ]
  then
    git config --global --replace-all user.name "$git_name"
fi

git config --global core.editor 'nvim --noplugin'
git config --global merge.tool 'meld'
git config --global color.ui 'auto'
git config --global color.grep.filename 'magenta'
git config --global color.grep.linenumber 'blue'
git config --global color.grep.match 'green'
git config --global push.default 'simple'

git config --global alias.au 'add -u'
git config --global alias.ai 'add -i'
git config --global alias.ap 'add -p'
git config --global alias.ci 'commit'
git config --global alias.co 'checkout'
git config --global alias.cp 'cherry-pick'
git config --global alias.br 'branch'
git config --global alias.l 'log --graph --decorate --pretty=oneline --abbrev-commit'
git config --global alias.la 'log --graph --decorate --pretty=oneline --abbrev-commit --all'
git config --global alias.ld "log --graph --decorate --pretty=format:'%Cred%h%Creset - %Cgreen(%cr)%Creset %s%C(yellow)%d%Creset' --abbrev-commit --date=iso"
git config --global alias.s 'status -s'
git config --global alias.d 'diff'
git config --global alias.dw 'diff --color-words -w -b'
git config --global alias.ds 'diff --staged'
git config --global alias.dsw 'diff --staged --color-words -w -b'
git config --global alias.g 'grep --break --heading --line-number'
git config --global alias.rso 'remote show origin'
git config --global alias.rpo 'remote prune origin'
git config --global alias.sl 'stash list'
git config --global alias.ss 'stash show'
