version: "3"

tasks:
  format:
    cmds:
      - stylua .

  clear-rr-cache:
    cmds:
      - rm -rf .git/rr-cache

  clear-nvim-plugins:
    cmds:
      - rm -rf ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim
