# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

###########
# https://starship.rs/config/#options
###########
# Timeout for starship to scan files (in milliseconds).
#   Default: 30
scan_timeout = 1000
# Timeout for commands executed by starship (in milliseconds).
#   Default: 500
command_timeout = 1000

# https://starship.rs/config/#command-duration
[cmd_duration]
disabled = true

# https://starship.rs/config/#direnv
[direnv]
disabled = false

# https://starship.rs/config/#package-version
[package]
display_private = true

# https://starship.rs/config/#status
# Display the exit code of the previous command if non-zero.
# [status]
# disabled = false

# https://starship.rs/config/#node-js
# [nodejs]
# disabled = true
