# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# https://starship.rs/config/#command-duration
[cmd_duration]
disabled = true

# https://starship.rs/config/#node-js
# [nodejs]
# disabled = true
