# See:
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default

gui:
  expandFocusedSidePanel: true
  theme:
    selectedLineBgColor:
      - '#dddddd'
    cherryPickedCommitBgColor:
      - '#000000'
    cherryPickedCommitFgColor:
      - '#00ff00'
