# See:
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default

# Theme:
# https://github.com/catppuccin/lazygit

gui:
  theme:
    selectedLineBgColor:
      - '#ccd0da'
    cherryPickedCommitBgColor:
      - '#bcc0cc'
    cherryPickedCommitFgColor:
      - '#179299'
